"use client";
import Image from "next/image";
import { usePathname } from "next/navigation";

const ImageWithContent: React.FC<{
	imageSrc: string;
	altText: string;
	children: React.ReactNode;
}> = ({ imageSrc, altText, children }) => {
	return (
		<>
			<div className="relative w-4/5 lg:w-7/12 h-[300px] md:h-[400px] lg:h-[500px] shadow-[0_0_4px_gray] hover:shadow-[0_0_4px_red] rounded-2xl overflow-hidden my-4">
				<Image
					src={imageSrc}
					alt={altText}
					fill
					sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
					className="object-cover"
				/>
			</div>
			<div className="max-w-2xl mx-auto p-4">{children}</div>
		</>
	);
};

const Solar = () => {
	return (
		<ImageWithContent imageSrc="/solar-new.jpg" altText="Solar panels">
			<div className="max-w-2xl mx-auto p-4">
				<h1 className="text-3xl font-bold mb-4">
					The Process of Harvesting Solar Energy: A Step-by-Step Guide
				</h1>
				<p className="mb-4">
					Solar energy is one of the most abundant and sustainable sources of
					power available today. As we move towards a reder future,
					understanding how solar energy is harnessed can give us insight into
					why it’s such a valuable resource. This blog explores the step-by-step
					process of how solar energy is harvested and transformed into
					electricity that powers our homes and businesses.
				</p>

				<h2 className="text-2xl font-semibold mb-2">
					1. <strong>Absorbing Solar Radiation</strong>
				</h2>
				<p className="mb-4">
					The first step in harvesting solar energy begins with the{" "}
					<strong>absorption of sunlight</strong> by solar panels, which are
					composed of <strong>photovoltaic (PV) cells</strong>. These cells are
					typically made from semiconductor materials like silicon, which have
					the unique ability to absorb sunlight in the form of photons (light
					particles).
				</p>

				<h2 className="text-2xl font-semibold mb-2">
					2. <strong>Exciting Electrons</strong>
				</h2>
				<p className="mb-4">
					When sunlight hits the photovoltaic cells, the energy from the photons
					causes the electrons in the semiconductor material to become excited.
					This phenomenon is known as the <strong>photoelectric effect</strong>,
					a key principle in converting sunlight into electricity. The excited
					electrons break free from their atoms and begin to move, creating an
					electric flow within the solar cell.
				</p>

				<h2 className="text-2xl font-semibold mb-2">
					3. <strong>Generating Electric Current</strong>
				</h2>
				<p className="mb-4">
					As the electrons start moving, they create a{" "}
					<strong>direct current (DC)</strong> within the solar panel. This is
					the raw form of electricity generated by solar panels. To capture this
					energy, the solar cells are connected with wires, which allow the
					direct current to be collected and directed to an inverter.
				</p>

				<h2 className="text-2xl font-semibold mb-2">
					4. <strong>Converting DC to Usable AC Power</strong>
				</h2>
				<p className="mb-4">
					While solar panels produce direct current (DC), most homes and
					businesses use <strong>alternating current (AC)</strong> to power
					devices and appliances. This is where the <strong>inverter</strong>{" "}
					comes into play. The inverter’s role is to convert the DC generated by
					the solar panels into usable AC electricity. Once converted, this
					electricity can be used to power everything from lights and appliances
					to larger industrial equipment.
				</p>

				<h2 className="text-2xl font-semibold mb-2">
					5. <strong>Distributing Electricity</strong>
				</h2>
				<p className="mb-4">
					Once converted to alternating current, the electricity is distributed
					in one of two ways:
				</p>
				<ul className="list-disc list-inside mb-4">
					<li>
						<strong>Immediate Use</strong>: The electricity can be directly used
						to power a home, office, or industrial facility.
					</li>
					<li>
						<strong>Grid Distribution</strong>: If the solar system produces
						more energy than is needed, the excess electricity can be sent back
						to the power grid. Many homeowners and businesses participate in{" "}
						<strong>net metering</strong>, a system that allows them to receive
						credits for the excess energy they send to the grid, effectively
						reducing their energy bills.
					</li>
				</ul>

				<h2 className="text-2xl font-semibold mb-2">
					6. <strong>Storing Excess Energy</strong>
				</h2>
				<p className="mb-4">
					While solar panels generate electricity during the day, they don’t
					work at night or during cloudy periods. To ensure power availability
					during those times, many solar systems include{" "}
					<strong>battery storage</strong> solutions. Energy stored in these
					batteries can be used when solar production is low, providing a
					reliable, round-the-clock energy supply. Popular energy storage
					systems, like <strong>Tesla Powerwall</strong>, allow for this
					flexibility.
				</p>

				<h2 className="text-2xl font-semibold mb-2">
					7. <strong>Monitoring and Optimization</strong>
				</h2>
				<p className="mb-4">
					Modern solar energy systems often come with{" "}
					<strong>monitoring software</strong> that tracks energy production,
					consumption, and efficiency. By analyzing this data, users can
					optimize their solar energy systems to ensure they are running at
					maximum efficiency. These insights can help adjust for weather
					patterns, maintenance needs, and usage habits, ensuring the system
					provides the most cost-effective power possible.
				</p>

				<hr className="my-4" />

				<h1 className="text-3xl font-bold mb-4">
					Why Solar Energy is the Future
				</h1>
				<p className="mb-4">
					The ability to harvest clean, renewable energy from the sun is an
					incredible achievement in the journey towards sustainability. By
					converting sunlight into electricity, we reduce our dependence on
					fossil fuels, lower our carbon footprint, and create a more resilient
					energy infrastructure. The solar energy harvesting process is
					efficient, environmentally friendly, and continuously improving with
					advancements in technology.
				</p>
				<p className="mb-4">
					Whether you’re considering installing solar panels for your home or
					just curious about how they work, understanding this process
					highlights why solar power is a key player in the global shift toward
					renewable energy. As the technology becomes more affordable and
					accessible, the future of solar energy looks brighter than ever.
				</p>

				<hr className="my-4" />

				<p className="mb-4">
					By understanding how solar energy is harvested, we can appreciate the
					potential it has to reshape our energy landscape and contribute to a
					more sustainable world. Solar power is more than just a trend—it’s the
					future of energy.
				</p>
			</div>
		</ImageWithContent>
	);
};

const Wind = () => {
	return (
		<ImageWithContent imageSrc="/wind-web.jpg" altText="Solar panels">
			<div className="max-w-2xl mx-auto p-4">
				<h3 className="text-2xl font-bold mb-4">
					The Process of Harvesting Wind Energy: Harnessing the Power of the Air
				</h3>
				<p className="mb-4">
					Wind energy has become one of the fastest-growing sources of renewable
					energy, providing a clean and efficient alternative to traditional
					power generation. From wind farms to small-scale turbines, wind energy
					harnesses the natural movement of air to generate electricity. In this
					blog, we’ll walk through the process of harvesting wind energy and
					explain how this invisible force is transformed into usable power.
				</p>

				<h4 className="text-xl font-semibold mb-2">
					1. <strong>Capturing Wind with Turbines</strong>
				</h4>
				<p className="mb-4">
					The process of harvesting wind energy begins with{" "}
					<strong>wind turbines</strong>—the large, often towering structures
					with blades that turn when the wind blows. Wind turbines work
					similarly to airplane wings. As the wind moves across the blades, it
					creates <strong>lift</strong>, causing the blades to spin. The{" "}
					<strong>rotor blades</strong> of the turbine capture the kinetic
					energy of the wind. The stronger the wind, the faster the blades spin.
					Modern wind turbines are designed to start operating at wind speeds as
					low as 5 to 8 mph (2 to 3.5 m/s), and they can safely shut down during
					extremely high wind speeds to prevent damage.
				</p>

				<h4 className="text-xl font-semibold mb-2">
					2. <strong>Converting Kinetic Energy into Mechanical Energy</strong>
				</h4>
				<p className="mb-4">
					As the wind spins the blades, the rotor (which consists of the blades
					and a central hub) rotates. This <strong>mechanical energy</strong>{" "}
					generated by the rotation is transferred to a <strong>shaft</strong>{" "}
					inside the turbine. The shaft is connected to a{" "}
					<strong>gearbox</strong>, which increases the rotational speed. This
					gearing mechanism ensures that the slow rotation of the blades is sped
					up enough to efficiently drive the next component—the generator.
				</p>

				<h4 className="text-xl font-semibold mb-2">
					3. <strong>Generating Electricity</strong>
				</h4>
				<p className="mb-4">
					At the heart of the wind turbine is the <strong>generator</strong>,
					which is responsible for converting the mechanical energy into{" "}
					<strong>electrical energy</strong>. Inside the generator, the spinning
					shaft turns a series of magnets around a coil of wire, creating an
					electric current through the principle of electromagnetic induction.
					This electric current is in the form of{" "}
					<strong>alternating current (AC)</strong>, which is used to power
					homes, businesses, and industries. The amount of electricity generated
					depends on both the wind speed and the size of the turbine. Larger
					turbines with longer blades can capture more wind and generate more
					power, making them suitable for wind farms, while smaller turbines are
					often used for residential or small commercial applications.
				</p>

				<h4 className="text-xl font-semibold mb-2">
					4. <strong>Transmitting Power to the Grid</strong>
				</h4>
				<p className="mb-4">
					Once the wind turbine generates electricity, it must be{" "}
					<strong>transmitted</strong> to where it’s needed. The electricity
					flows from the generator through power cables to a{" "}
					<strong>transformer</strong>, which steps up the voltage so the
					electricity can be transmitted over long distances via the{" "}
					<strong>power grid</strong>. At wind farms, where multiple turbines
					are installed, the electricity from all the turbines is collected and
					sent through a central transformer before being transmitted to the
					grid. This power is then distributed to homes and businesses for use.
				</p>

				<h4 className="text-xl font-semibold mb-2">
					5. <strong>Monitoring and Controlling the Turbine</strong>
				</h4>
				<p className="mb-4">
					Wind turbines are equipped with <strong>monitoring systems</strong>{" "}
					that track their performance, wind conditions, and the amount of
					energy generated. The turbine’s control system can automatically
					adjust the angle of the blades (called <strong>pitch control</strong>)
					to optimize the efficiency of energy generation based on the wind
					speed and direction. In addition to pitch control, turbines use{" "}
					<strong>yaw control</strong> to rotate the entire structure so that
					the blades always face into the wind. This ensures that the turbine
					captures the maximum possible amount of wind energy.
				</p>

				<h4 className="text-xl font-semibold mb-2">
					6. <strong>Storing Excess Energy (Optional)</strong>
				</h4>
				<p className="mb-4">
					Like other renewable energy sources, wind energy can sometimes produce
					more electricity than is immediately needed. In these cases,{" "}
					<strong>energy storage systems</strong> can be used to capture the
					excess electricity for later use. Battery storage solutions, such as{" "}
					<strong>lithium-ion batteries</strong>, are increasingly paired with
					wind farms to store surplus energy, making it available during periods
					when the wind isn’t blowing.
				</p>

				<h4 className="text-xl font-semibold mb-2">
					7. <strong>The Role of Wind Farms</strong>
				</h4>
				<p className="mb-4">
					While individual wind turbines are common for residential use,
					large-scale <strong>wind farms</strong> are critical for generating
					enough electricity to meet the energy demands of cities and
					industries. A wind farm consists of many turbines spread over a wide
					area, all working together to produce vast amounts of electricity.
					Wind farms are typically located in regions with consistently strong
					winds, such as coastal areas, open plains, and offshore locations.
					Offshore wind farms, in particular, are gaining popularity due to the
					higher and more consistent wind speeds over oceans and seas.
				</p>

				<hr className="my-6" />

				<h3 className="text-2xl font-bold mb-4">
					Why Wind Energy is Essential for a Sustainable Future
				</h3>
				<p className="mb-4">
					Wind energy offers numerous benefits as a renewable energy source. It
					is clean, meaning it produces no redhouse gas emissions or air
					pollutants. It is also <strong>sustainable</strong>, as wind is a
					natural and inexhaustible resource. Once a wind turbine is installed,
					it can generate electricity for decades with minimal environmental
					impact. Wind energy also plays a crucial role in reducing our
					dependence on fossil fuels, which helps combat climate change. The
					global shift towards renewable energy sources is being led by wind and
					solar energy, both of which offer scalable solutions to meet the
					growing demand for clean electricity.
				</p>

				<hr className="my-6" />

				<h3 className="text-2xl font-bold mb-4">
					Conclusion: The Power of Wind Energy
				</h3>
				<p className="mb-4">
					Wind energy is a powerful and efficient way to generate electricity,
					harnessing the natural movement of air to power our world. From
					capturing the wind’s kinetic energy to transmitting it to the grid,
					the process is a testament to the ingenuity of modern technology. With
					continuous advancements in turbine design, energy storage, and grid
					integration, wind energy is poised to become an even more significant
					part of our energy future. As we look toward a more sustainable world,
					investing in wind energy is a crucial step in reducing carbon
					emissions and ensuring a cleaner, reder planet for future generations.
					The next time you see a wind turbine spinning on the horizon, remember
					that it’s not just catching the wind—it’s capturing the future of
					energy.
				</p>
			</div>
		</ImageWithContent>
	);
};

const Hydrogen = () => {
	return (
		<ImageWithContent imageSrc="/hydrogen.png" altText="Solar panels">
			<div className="max-w-2xl mx-auto p-4">
				<h1 className="text-3xl font-bold mb-4">
					Understanding Hydrogen Power Plants: A Comprehensive Guide
				</h1>
				<p className="mb-4">
					As the world seeks cleaner and more sustainable energy sources,
					hydrogen power is emerging as a promising solution. This blog explores
					the fundamentals of hydrogen power plants, their functioning,
					advantages, challenges, and future prospects.
				</p>

				<h2 className="text-2xl font-semibold mb-2">What is Hydrogen Power?</h2>
				<p className="mb-4">
					Hydrogen power involves using hydrogen as a fuel to generate
					electricity. It can be harnessed through various methods, primarily by
					burning hydrogen or using fuel cells. When hydrogen is burned, it
					produces water vapor and energy. Fuel cells convert hydrogen directly
					into electricity through an electrochemical process, emitting only
					water and heat as byproducts.
				</p>

				<h3 className="text-xl font-semibold mb-2">
					Types of Hydrogen Production
				</h3>
				<ol className="list-decimal list-inside mb-4">
					<li>
						<strong>Steam Methane Reforming (SMR)</strong>: The most common
						method, SMR, involves reacting natural gas (methane) with steam to
						produce hydrogen. While efficient, this process emits carbon
						dioxide, raising concerns about its environmental impact.
					</li>
					<li>
						<strong>Electrolysis</strong>: This method uses electricity to split
						water into hydrogen and oxygen. When powered by renewable energy
						sources, electrolysis can produce &quot;red hydrogen,&quot; making
						it a clean alternative.
					</li>
					<li>
						<strong>Gasification</strong>: Biomass and coal can be converted
						into hydrogen through gasification, where high temperatures break
						down organic materials.
					</li>
					<li>
						<strong>Photoelectrochemical (PEC) Water Splitting</strong>:
						Emerging technology utilizes sunlight to directly split water
						molecules into hydrogen and oxygen.
					</li>
				</ol>

				<h3 className="text-xl font-semibold mb-2">
					How Do Hydrogen Power Plants Work?
				</h3>
				<p className="mb-4">
					Hydrogen power plants can be categorized primarily into two types:{" "}
					<strong>hydrogen combustion power plants</strong> and{" "}
					<strong>hydrogen fuel cell power plants</strong>.
				</p>

				<h4 className="text-lg font-semibold mb-2">
					Hydrogen Combustion Power Plants
				</h4>
				<ol className="list-decimal list-inside mb-4">
					<li>
						<strong>Combustion Process</strong>: In these plants, hydrogen is
						burned in turbines to generate steam. The steam drives turbines,
						which produce electricity. The overall process is similar to natural
						gas power plants but with cleaner emissions.
					</li>
					<li>
						<strong>Blending with Natural Gas</strong>: Some plants blend
						hydrogen with natural gas to reduce carbon emissions. This hybrid
						approach allows for a gradual transition to hydrogen without
						requiring significant infrastructure changes.
					</li>
				</ol>

				<h4 className="text-lg font-semibold mb-2">
					Hydrogen Fuel Cell Power Plants
				</h4>
				<ol className="list-decimal list-inside mb-4">
					<li>
						<strong>Electrochemical Reaction</strong>: Fuel cells convert
						hydrogen and oxygen into electricity, water, and heat through an
						electrochemical process. This reaction occurs in the anode and
						cathode, with a proton exchange membrane facilitating the flow of
						protons.
					</li>
					<li>
						<strong>Advantages</strong>: Fuel cells are highly efficient and can
						be scaled for various applications, from small devices to large
						power plants.
					</li>
				</ol>

				<h3 className="text-xl font-semibold mb-2">
					Advantages of Hydrogen Power Plants
				</h3>
				<ol className="list-decimal list-inside mb-4">
					<li>
						<strong>Environmental Benefits</strong>: Hydrogen power produces
						minimal emissions, particularly when using red hydrogen. The only
						byproducts are water and heat, making it an attractive alternative
						to fossil fuels.
					</li>
					<li>
						<strong>Energy Storage</strong>: Hydrogen can be stored for long
						periods, helping balance supply and demand in renewable energy
						systems. It can act as a buffer for excess energy generated from
						solar or wind sources.
					</li>
					<li>
						<strong>Versatility</strong>: Hydrogen can be used across various
						sectors, including transportation, heating, and industrial
						processes, making it a versatile energy carrier.
					</li>
					<li>
						<strong>Energy Security</strong>: Hydrogen can be produced from
						diverse sources, reducing dependence on specific fossil fuels and
						enhancing energy security.
					</li>
				</ol>

				<h3 className="text-xl font-semibold mb-2">
					Challenges Facing Hydrogen Power
				</h3>
				<ol className="list-decimal list-inside mb-4">
					<li>
						<strong>Production Costs</strong>: While red hydrogen production
						costs are decreasing, they remain higher than fossil fuels.
						Continued investment in research and development is needed to
						improve efficiency and reduce costs.
					</li>
					<li>
						<strong>Infrastructure Development</strong>: Existing infrastructure
						for natural gas may not be suitable for hydrogen transport and
						storage. Significant investments are required to develop hydrogen
						pipelines, storage facilities, and refueling stations.
					</li>
					<li>
						<strong>Safety Concerns</strong>: Hydrogen is highly flammable and
						requires careful handling. Public perception and safety regulations
						need to be addressed to promote widespread adoption.
					</li>
					<li>
						<strong>Energy Efficiency</strong>: The processes involved in
						producing, storing, and utilizing hydrogen can result in energy
						losses. Ensuring high efficiency throughout the hydrogen supply
						chain is crucial for its viability.
					</li>
				</ol>

				<h3 className="text-xl font-semibold mb-2">Current Global Landscape</h3>
				<p className="mb-4">
					Countries around the world are investing in hydrogen technologies as
					part of their energy transition strategies. Notable initiatives
					include:
				</p>
				<ul className="list-disc list-inside mb-4">
					<li>
						<strong>European Union</strong>: The EU has set ambitious hydrogen
						production targets, aiming for 10 million tons of red hydrogen by
						2030.
					</li>
					<li>
						<strong>United States</strong>: Various federal and state programs
						are supporting hydrogen research and infrastructure development,
						particularly in transportation.
					</li>
					<li>
						<strong>Japan and South Korea</strong>: These countries are leading
						in hydrogen technology and infrastructure, aiming to create
						hydrogen-based economies.
					</li>
				</ul>

				<h3 className="text-xl font-semibold mb-2">Future Prospects</h3>
				<p className="mb-4">
					The future of hydrogen power looks promising, with potential
					developments including:
				</p>
				<ol className="list-decimal list-inside mb-4">
					<li>
						<strong>Technological Advancements</strong>: Ongoing research into
						more efficient production methods, improved fuel cells, and enhanced
						storage solutions can significantly lower costs and increase
						adoption.
					</li>
					<li>
						<strong>Integration with Renewables</strong>: As renewable energy
						sources expand, the integration of hydrogen production through
						electrolysis can help stabilize energy grids and maximize the use of
						clean energy.
					</li>
					<li>
						<strong>International Hydrogen Economy</strong>: As hydrogen becomes
						a key energy carrier, international collaboration for trade and
						technology transfer can facilitate its global adoption.
					</li>
					<li>
						<strong>Policy Support</strong>: Governments can play a crucial role
						by implementing supportive policies, subsidies, and incentives to
						encourage hydrogen research, development, and infrastructure
						investment.
					</li>
				</ol>

				<h2 className="text-2xl font-semibold mb-2">Conclusion</h2>
				<p className="mb-4">
					Hydrogen power plants represent a significant step towards a
					sustainable energy future. While challenges remain, the advantages of
					hydrogen as a clean energy carrier are undeniable. Continued
					investment in technology and infrastructure, coupled with supportive
					policies, will pave the way for hydrogen&apos;s role in the global
					energy landscape. As we move forward, hydrogen could become an
					integral part of our efforts to combat climate change and create a
					sustainable energy system for generations to come.
				</p>
			</div>
		</ImageWithContent>
	);
};

const Ethanol = () => {
	return (
		<ImageWithContent imageSrc="/eth.jpg" altText="Solar panels">
			<div className="max-w-2xl mx-auto p-4">
				<h1 className="text-4xl font-bold mb-6">
					Understanding Ethanol Plants: A Comprehensive Guide
				</h1>
				<p className="mb-4">
					As the global energy landscape shifts towards sustainable and
					renewable sources, ethanol has emerged as a key player in the quest
					for cleaner fuel alternatives. This blog explores the fundamentals of
					ethanol plants, their functioning, advantages, challenges, and future
					prospects.
				</p>

				<h2 className="text-3xl font-semibold mb-4">What is Ethanol?</h2>
				<p className="mb-4">
					Ethanol, also known as ethyl alcohol, is a renewable fuel made
					primarily from plant materials. It can be used as a standalone fuel or
					blended with gasoline to reduce emissions and enhance octane levels.
					Ethanol is commonly derived from crops such as corn, sugarcane, and
					other biomass materials.
				</p>

				<h3 className="text-2xl font-semibold mb-3">
					Types of Ethanol Production
				</h3>
				<ul className="list-disc list-inside mb-4">
					<li>
						<strong>Corn Ethanol</strong>: The most prevalent form in the United
						States, corn ethanol is produced through a fermentation process that
						converts starches in corn into sugars, which are then fermented into
						alcohol.
					</li>
					<li>
						<strong>Sugarcane Ethanol</strong>: Predominantly produced in
						Brazil, sugarcane ethanol involves extracting juice from the cane
						and fermenting it directly into ethanol. It offers higher yields
						compared to corn.
					</li>
					<li>
						<strong>Cellulosic Ethanol</strong>: This next-generation biofuel is
						produced from non-food plant materials, such as wood chips,
						agricultural residues, and grasses. Cellulosic ethanol has the
						potential to significantly reduce redhouse gas emissions.
					</li>
					<li>
						<strong>Waste Ethanol</strong>: Ethanol can also be produced from
						waste materials, including food scraps and industrial waste,
						providing a sustainable recycling option.
					</li>
				</ul>

				<h3 className="text-2xl font-semibold mb-3">
					How Do Ethanol Plants Work?
				</h3>
				<ol className="list-decimal list-inside mb-4 space-y-3">
					<li>
						<strong>Feedstock Preparation</strong>: Raw materials, such as corn
						or sugarcane, are processed to extract sugars. In the case of corn,
						it is ground into a fine powder and mixed with water.
					</li>
					<li>
						<strong>Hydrolysis</strong>: For starch-based feedstocks like corn,
						enzymes are added to break down starches into fermentable sugars.
					</li>
					<li>
						<strong>Fermentation</strong>: Yeast is introduced to the mixture,
						which ferments the sugars into ethanol and carbon dioxide.
					</li>
					<li>
						<strong>Distillation</strong>: Distillation separates ethanol from
						the water and solids, yielding a higher concentration of ethanol.
					</li>
					<li>
						<strong>Dehydration</strong>: The distilled ethanol is dehydrated to
						remove remaining water, resulting in anhydrous ethanol suitable for
						fuel.
					</li>
					<li>
						<strong>Denaturing</strong>: Fuel ethanol is denatured by adding
						chemicals to make it undrinkable.
					</li>
					<li>
						<strong>Storage and Distribution</strong>: The final product is
						stored and distributed to blending facilities or other end-users.
					</li>
				</ol>

				<h3 className="text-2xl font-semibold mb-3">
					Advantages of Ethanol Plants
				</h3>
				<ul className="list-disc list-inside mb-4">
					<li>
						<strong>Renewable Resource</strong>: Ethanol is produced from
						biomass, making it a renewable energy source.
					</li>
					<li>
						<strong>Lower Emissions</strong>: Ethanol burns cleaner than
						gasoline, resulting in lower redhouse gas emissions.
					</li>
					<li>
						<strong>Economic Benefits</strong>: Ethanol production supports
						agricultural economies and creates jobs.
					</li>
					<li>
						<strong>Energy Security</strong>: Ethanol contributes to national
						energy security by diversifying the fuel supply.
					</li>
				</ul>

				<h3 className="text-2xl font-semibold mb-3">
					Challenges Facing Ethanol Production
				</h3>
				<ul className="list-disc list-inside mb-4">
					<li>
						<strong>Land Use Concerns</strong>: Growing crops for ethanol can
						compete with food production and raise sustainability concerns.
					</li>
					<li>
						<strong>Water Use</strong>: Ethanol production can be
						water-intensive, requiring sustainable water management practices.
					</li>
					<li>
						<strong>Energy Balance</strong>: The energy input for ethanol
						production can approach or exceed the energy output, especially for
						corn-based ethanol.
					</li>
					<li>
						<strong>Carbon Footprint</strong>: While ethanol reduces emissions
						when burned, its production can generate carbon emissions.
					</li>
				</ul>

				<h3 className="text-2xl font-semibold mb-3">
					Current Global Landscape
				</h3>
				<ul className="list-disc list-inside mb-4">
					<li>
						<strong>United States</strong>: The U.S. is the largest producer of
						ethanol, primarily from corn.
					</li>
					<li>
						<strong>Brazil</strong>: Brazil is a leader in sugarcane ethanol
						production, with well-established infrastructure.
					</li>
					<li>
						<strong>European Union</strong>: The EU promotes biofuels, including
						ethanol, as part of its renewable energy policies.
					</li>
				</ul>

				<h3 className="text-2xl font-semibold mb-3">Future Prospects</h3>
				<ul className="list-disc list-inside mb-4">
					<li>
						<strong>Technological Advancements</strong>: Research into more
						efficient processes can enhance yields and reduce costs.
					</li>
					<li>
						<strong>Sustainable Practices</strong>: Precision farming and
						sustainable agriculture are becoming industry priorities.
					</li>
					<li>
						<strong>Cellulosic Ethanol</strong>: This technology is expected to
						grow, utilizing waste materials and non-food crops.
					</li>
					<li>
						<strong>Integration with Other Renewable Fuels</strong>: Ethanol can
						be combined with other biofuels to create a more sustainable fuel
						portfolio.
					</li>
				</ul>

				<h3 className="text-2xl font-semibold mb-3">Conclusion</h3>
				<p className="mb-4">
					Ethanol plants play a vital role in the transition to sustainable
					energy. While challenges exist, the benefits of ethanol as a renewable
					fuel are significant. With continued innovation and a focus on
					sustainability, ethanol has the potential to become an integral part
					of a cleaner, more resilient energy future.
				</p>
			</div>
		</ImageWithContent>
	);
};

export default function Page() {
	const pathname = usePathname();

	switch (pathname) {
		case "/energy/solar":
			return <Solar />;
		case "/energy/wind":
			return <Wind />;
		case "/energy/hydrogen":
			return <Hydrogen />;
		case "/energy/ethanol":
			return <Ethanol />;
		default:
			return <Ethanol />;
	}
}
